apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "64Mi"
          cpu: "500m" # 0,5 cpu
      ports:
        - containerPort: 3000
