version: "3"
services:
  postgres:
    image: "postgres:latest"
    container_name: fibonacci-calc_postgres_dev
    ports:
      - "5433:5432"
  redis:
    image: "redis:latest"
    container_name: fibonacci-calc_redis_dev
  proxy:
    image: joma74/udemy-docker-k8s-tcg/fibonacci-calc/proxy/dev:latest
    build:
      dockerfile: Dockerfile
      context: ./fibonacci-calc-proxy
    depends_on:
      - api
      - frontend
    container_name: fibonacci-calc_proxy_dev
    restart: always
    ports:
      - "3050:80"
    volumes:
      - ./fibonacci-calc-proxy/nginx.conf:/etc/nginx/conf.d/default.conf # do mount this over
  api:
    image: joma74/udemy-docker-k8s-tcg/fibonacci-calc/api/dev:latest
    build:
      dockerfile: Dockerfile.dev
      context: ./fibonacci-calc-server
    depends_on:
      - postgres
      - redis
    container_name: fibonacci-calc_api_dev
    # explore to name service "server" but be reachable via "api"
    # networks:
    #  default:
    #    aliases:
    #      - api
    volumes:
      - /usr/app/node_modules # do NOT mount this over
      - ./fibonacci-calc-server/package.json:/usr/app/package.json # do mount this over
      - ./fibonacci-calc-server/yarn.lock:/usr/app/yarn.lock # do mount this over
      - ./fibonacci-calc-server/src:/usr/app/src # do mount this over
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  frontend:
    image: joma74/udemy-docker-k8s-tcg/fibonacci-calc/frontend/dev:latest
    build:
      dockerfile: Dockerfile.dev
      context: ./fibonacci-calc-frontend
    container_name: fibonacci-calc_frontend_dev
    depends_on:
      - api
    volumes:
      - /usr/app/node_modules # do NOT mount this over
      - ./fibonacci-calc-frontend/package.json:/usr/app/package.json # do mount this over
      - ./fibonacci-calc-frontend/yarn.lock:/usr/app/yarn.lock # do mount this over
      - ./fibonacci-calc-frontend/src:/usr/app/src # do mount this over
      - ./fibonacci-calc-frontend/public:/usr/app/public # do mount this over
  worker:
    image: joma74/udemy-docker-k8s-tcg/fibonacci-calc/worker/dev:latest
    build:
      dockerfile: Dockerfile.dev
      context: ./fibonacci-calc-worker
    depends_on:
      - redis
    container_name: fibonacci-calc_worker_dev
    volumes:
      - /usr/app/node_modules # do NOT mount this over
      - ./fibonacci-calc-worker/package.json:/usr/app/package.json # do mount this over
      - ./fibonacci-calc-worker/yarn.lock:/usr/app/yarn.lock # do mount this over
      - ./fibonacci-calc-worker/src:/usr/app/src # do mount this over
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
